from .Node import Node
from .Module import Module
from .Comment import Comment
from .LineComment import LineComment
from .BlockComment import BlockComment
from .Include import Include
from .Newline import Newline
from .Call import Call
from .Declaration import Declaration
from .Function import Function
from .Implementation import Implementation
from .Array import Array
from .Value import Value
from .FuncDef import FuncDef
from .FuncImpl import FuncImpl
from .Compare import Compare
from .If import If
from .Assign import Assign
